server:
  port: 9090 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

zuul:
  routes:
    commande-service:
      path: /commande/**
      serviceId: microservice-commande
    commandes-v2-service:
      path: /commandesV2/**
      serviceId: microservice-commande-produit
    produits-service:
      path: /produits/**
      serviceId: microservice-commande-produit
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG
